import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';
import {
  LucideActivity,
  LucideAlertTriangle,
  LucideBuilding2,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircle,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleHelp,
  LucideContrast,
  LucideCopy,
  LucideDatabase,
  LucideDownload,
  LucideEdit,
  LucideEye,
  LucideEyeOff,
  LucideHardDrive,
  LucideHouse,
  LucideInbox,
  LucideInfo,
  LucideKeyRound,
  LucideLink,
  LucideLoaderCircle,
  LucideLockKeyhole,
  LucideLogOut,
  LucideMail,
  LucideMailCheck,
  LucideMessageCircle,
  LucideMonitor,
  LucideMonitorOff,
  LucideMoon,
  LucideMenu,
  LucidePanelLeft,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePlus,
  LucideQrCode,
  LucideRefreshCw,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideShieldCheck,
  LucideShieldX,
  LucideShoppingBag,
  LucideSun,
  LucideTrash2,
  LucideTriangleAlert,
  LucideUserRound,
  LucideUsers,
  LucideX,
  provideLucideConfig,
  provideLucideIcons,
} from '@lucide/angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { provideSentry } from './core/monitoring/sentry';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    ...provideSentry(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAnimations(),
    provideLucideConfig({ size: 18, strokeWidth: 2, absoluteStrokeWidth: true }),
    provideLucideIcons(
      LucideActivity,
      LucideAlertTriangle,
      LucideBuilding2,
      LucideCheck,
      LucideChevronDown,
      LucideChevronRight,
      LucideCircle,
      LucideCircleAlert,
      LucideCircleCheck,
      LucideCircleHelp,
      LucideContrast,
      LucideCopy,
      LucideDatabase,
      LucideDownload,
      LucideEdit,
      LucideEye,
      LucideEyeOff,
      LucideHardDrive,
      LucideHouse,
      LucideInbox,
      LucideInfo,
      LucideKeyRound,
      LucideLink,
      LucideLoaderCircle,
      LucideLockKeyhole,
      LucideLogOut,
      LucideMail,
      LucideMailCheck,
      LucideMessageCircle,
      LucideMonitor,
      LucideMonitorOff,
      LucideMoon,
      LucideMenu,
      LucidePanelLeft,
      LucidePanelLeftClose,
      LucidePanelLeftOpen,
      LucidePlus,
      LucideQrCode,
      LucideRefreshCw,
      LucideSearch,
      LucideServer,
      LucideSettings,
      LucideShieldCheck,
      LucideShieldX,
      LucideShoppingBag,
      LucideSun,
      LucideTrash2,
      LucideTriangleAlert,
      LucideUserRound,
      LucideUsers,
      LucideX,
    ),
  ],
};
